version: 1.0.{build}
install:
- git submodule update --init --recursive
- pwsh: scripts/lib/init.ps1
- pwsh: scripts/lib/restore.ps1
- pwsh: ipmo require; req configmap
- pwsh: qbuild init
- pwsh: qbuild restore
build_script:
- pwsh: qbuild build
- pwsh: write-host "no need to build powershell"
test_script:
- pwsh: qbuild test
artifacts:
- path: artifacts
- path: src/publishmap
deploy_script:
- pwsh: qbuild push . -buildno $env:APPVEYOR_BUILD_NUMBER